# Generated by Django 4.1.7 on 2023-03-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_name', models.CharField(max_length=500, verbose_name='اسم المنتج')),
                ('prd_price', models.FloatField(default=0, verbose_name='السعر')),
                ('description', models.CharField(max_length=1500, verbose_name='الوصف')),
                ('img', models.ImageField(default='media/prd/default.png', upload_to='media/prd/', verbose_name='صورة المنتج')),
                ('up_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('recommended', models.BooleanField(verbose_name='يعرض على الرئيسية')),
                ('sold', models.BooleanField(verbose_name='مباع')),
                ('unit', models.CharField(default='', max_length=140, verbose_name='القياس')),
                ('discount', models.IntegerField(default=0, verbose_name='الخصم')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('total', models.FloatField(default=0, verbose_name='السعر الكلي')),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='القسم')),
            ],
        ),
    ]
