# Generated by Django 4.1.7 on 2023-04-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prd_price',
            field=models.IntegerField(default=0, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('جلسة', 'جلسة'), ('علبة', 'علبة'), ('قطعة', 'قطعة'), ('1غم', '1غم'), ('5غم', '5غم'), ('10غم', '10غم'), ('25غم', '25غم'), ('50', '50غم'), ('100غم', '100غم'), ('250غم', '250غم'), ('500غم', '500غم'), ('100كغم', '100كغم'), ('100مل', '100مل'), ('500مل', '500مل'), ('1لتر', '1 لتر')], default='', max_length=140, verbose_name='القياس'),
        ),
    ]
